<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>OstranautsWorkshopBepInExBridge.Preloader</AssemblyName>
    <RootNamespace>OstranautsWorkshopBepInExBridge.Preloader</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>bin\$(Configuration)\</OutputPath>
  </PropertyGroup>

  <PropertyGroup>
    <GameDir Condition="'$(GameDir)' == ''">..\..\..\Steam\steamapps\common\Ostranauts</GameDir>
    <BepInExDir Condition="'$(BepInExDir)' == ''">$(GameDir)\BepInEx</BepInExDir>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Mono.Cecil">
      <HintPath>$(BepInExDir)\core\Mono.Cecil.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
